### PR TITLE
Game and menu styling

### PR DESCRIPTION
**Pull request by ToniRib**
I added some styling and put in a fix so that the canvas can be anywhere on the page and the click events will still render correctly.

However, I ran into some bugs so I commented out some code because I can't figure it out.

1) I made a div with the id `number-of-lives` but when I try to call `document.getElementById('number-of-lives')` it returns null and won't get me get or set the text. You can see what I am trying to do on lines 56 - 58, and 62.
2) I want to eventually implement a "start level" or "call wave" button of some kind, so I figure we can wrap line 75 in an if statement that waits for that button to be clicked. However, before that, we would still want to render the board and any towers, and allow the user to build out the towers. I tried to do even just part of this (statically render the board) on line 68, but it renders nothing if I do that.

### CODE REVIEW

**Comment by ToniRib** [comment]
@stevekinney hoping you can help with some of the issues I outlined above. I can't figure out what I'm doing wrong.

**Comment by ToniRib** [comment]
Also adding @rrgayhart

**Comment by ToniRib** [comment]
This is what I get when I try to call `document.getElementById('number-of-lives').innerHTML();`

```
Uncaught TypeError: document.getElementById(...).innerHTML is not a function
```

**Comment by ToniRib** [comment]
Also if I run jQuery in the console:
```
$('#number-of-lives').text()
""
```

**Comment by rrgayhart** [comment]
@ToniRib - I think you might be getting a false-positive on the assumption that you can't grab number-of-lines.

So if you stick a debugger in that function - you can actually grab `document.getElementById('number-of-lives')` (but only after the document loads).

If you try to just do it in the chrome console, outside of the debugger statement, you don't find anything. The reason is that Webpack is displaying your page in an iFrame.. which is annoying.

I do still see the error you're talking about - I'll dig into that a little bit more!

**Comment by rrgayhart** [comment]
`innerHTML` without the `()` - so `innerHTML = 8`

**Comment by ToniRib** [comment]
@rrgayhart is a genius, so I fixed the issue with updating the number of lives.

**Comment by ToniRib** [comment]
This branch is now ready to merge in. Both of the errors above were fixed.

**Comment by Jlawlzz** [comment]
Looks great, like a real game now!

**Pull request merged**
